# Ensemble tests

Runs every ranker configuration in `CONFIGS` on every dataset in `DATASETS`, evaluates each run against `datasets/<name>/qrels/<QRELS_SPLIT>.tsv`, and collects the metrics in one table.

Vectors must already exist (`python src/encode.py --method <encoder>`). Use the **aws** kernel.

In [10]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from search import run_search

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Configure

Each entry in `CONFIGS` is `(label, ranker, options)`:
- `"chamfer"` takes `symmetric`.
- `"sw"` (sliced Wasserstein) takes `slices`, `quantiles`, `p`, `seed`. Slices are nested, so for one seed a larger `slices` extends a smaller one with more directions.

`IGNORE_IDENTICAL_IDS` lists datasets whose queries also appear in the corpus (BEIR convention: drop the self-match).

In [19]:
DATASETS = ["arguana", "scidocs", "quora"]
ENCODER = "bert"
QUERY_TAG = None      # only needed when a dataset has several vector sets for ENCODER
CORPUS_TAG = None
K = 100
QRELS_SPLIT = "test"
METRICS = ("ndcg@10", "recall@100", "mrr@10")
IGNORE_IDENTICAL_IDS = {"arguana"}
WRITE = True          # also save each run to results/<dataset>/<encoder>/

CONFIGS = [
    ("chamfer",     "chamfer", {}),
    ("chamfer-sym", "chamfer", {"symmetric": True}),
] + [
    (f"sw L={L}",   "sw",      {"slices": L, "quantiles": 32, "p": 2, "seed": 0})
    for L in (64, 128, 256, 512, 1024, 2048)
]

## Run

In [20]:
rows = []
for dataset in DATASETS:
    for label, ranker, opts in CONFIGS:
        out = run_search(dataset, ranker, ENCODER, QUERY_TAG, CORPUS_TAG, k=K,
                         ignore_identical_ids=dataset in IGNORE_IDENTICAL_IDS, write=WRITE,
                         qrels_split=QRELS_SPLIT, metrics=METRICS, **opts)
        meta = out["meta"]
        if "metrics" not in meta:
            print(f"  no qrels for {dataset}/{QRELS_SPLIT}; skipping evaluation")
        rows.append({"dataset": dataset, "config": label, **meta.get("metrics", {}),
                     "seconds": meta["seconds"]})

[arguana] chamfer: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (2s)
  ndcg@10=0.3414  recall@100=0.8208  mrr@10=0.2791
  wrote results/arguana/bert/chamfer__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[arguana] chamfer-sym: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (2s)
  ndcg@10=0.3435  recall@100=0.8201  mrr@10=0.2825
  wrote results/arguana/bert/chamfer-sym__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (3s)
[arguana] sw_L64_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.1159  recall@100=0.4950  mrr@10=0.0885
  wrote results/arguana/bert/sw_L64_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[arguana] sw_L128_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.1754  recall@100=0.6060  mrr@10=0.1349
  wrote results/arguana/bert/sw_L128_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[arguana] sw_L256_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.2089  recall@100=0.6465  mrr@10=0.1641
  wrote results/arguana/bert/sw_L256_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[arguana] sw_L512_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.2268  recall@100=0.6764  mrr@10=0.1785
  wrote results/arguana/bert/sw_L512_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[arguana] sw_L1024_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.2409  recall@100=0.6871  mrr@10=0.1902
  wrote results/arguana/bert/sw_L1024_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[arguana] sw_L2048_K32_p2_s0: 1406 queries x 8674 docs  device=cuda dtype=torch.float16
  8674/8674 docs  (1s)
  ndcg@10=0.2424  recall@100=0.6977  mrr@10=0.1922
  wrote results/arguana/bert/sw_L2048_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (1s)
[scidocs] chamfer: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (56s)
  ndcg@10=0.1043  recall@100=0.2636  mrr@10=0.2000
  wrote results/scidocs/bert/chamfer__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (57s)
[scidocs] chamfer-sym: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (5s)
  ndcg@10=0.0596  recall@100=0.2319  mrr@10=0.1086
  wrote results/scidocs/bert/chamfer-sym__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (5s)
[scidocs] sw_L64_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (2s)
  ndcg@10=0.0162  recall@100=0.0920  mrr@10=0.0320
  wrote results/scidocs/bert/sw_L64_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[scidocs] sw_L128_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (2s)
  ndcg@10=0.0269  recall@100=0.1187  mrr@10=0.0498
  wrote results/scidocs/bert/sw_L128_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[scidocs] sw_L256_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (2s)
  ndcg@10=0.0286  recall@100=0.1377  mrr@10=0.0558
  wrote results/scidocs/bert/sw_L256_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[scidocs] sw_L512_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (2s)
  ndcg@10=0.0327  recall@100=0.1468  mrr@10=0.0599
  wrote results/scidocs/bert/sw_L512_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[scidocs] sw_L1024_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (2s)
  ndcg@10=0.0359  recall@100=0.1539  mrr@10=0.0675
  wrote results/scidocs/bert/sw_L1024_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (2s)
[scidocs] sw_L2048_K32_p2_s0: 1000 queries x 25657 docs  device=cuda dtype=torch.float16
  25657/25657 docs  (3s)
  ndcg@10=0.0351  recall@100=0.1570  mrr@10=0.0645
  wrote results/scidocs/bert/sw_L2048_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (3s)
[quora] chamfer: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (304s)
  ndcg@10=0.6582  recall@100=0.8975  mrr@10=0.6543
  wrote results/quora/bert/chamfer__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (305s)
[quora] chamfer-sym: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (131s)
  ndcg@10=0.6593  recall@100=0.9039  mrr@10=0.6560
  wrote results/quora/bert/chamfer-sym__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (132s)
[quora] sw_L64_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (8s)
  ndcg@10=0.5442  recall@100=0.7904  mrr@10=0.5434
  wrote results/quora/bert/sw_L64_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (8s)
[quora] sw_L128_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (11s)
  ndcg@10=0.5811  recall@100=0.8315  mrr@10=0.5771
  wrote results/quora/bert/sw_L128_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (11s)
[quora] sw_L256_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (18s)
  ndcg@10=0.5916  recall@100=0.8432  mrr@10=0.5867
  wrote results/quora/bert/sw_L256_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (18s)
[quora] sw_L512_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (30s)
  ndcg@10=0.6017  recall@100=0.8534  mrr@10=0.5973
  wrote results/quora/bert/sw_L512_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (30s)
[quora] sw_L1024_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (55s)
  ndcg@10=0.6075  recall@100=0.8583  mrr@10=0.6029
  wrote results/quora/bert/sw_L1024_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (55s)
[quora] sw_L2048_K32_p2_s0: 15000 queries x 522931 docs  device=cuda dtype=torch.float16
  522931/522931 docs  (108s)
  ndcg@10=0.6090  recall@100=0.8601  mrr@10=0.6039
  wrote results/quora/bert/sw_L2048_K32_p2_s0__bert-base-uncased_d768_nv32__bert-base-uncased_d768_nv180.trec  (108s)

## Results

In [21]:
table = pd.DataFrame(rows)
table

    dataset       config  ndcg@10  recall@100  mrr@10  seconds
0   arguana      chamfer   0.3414      0.8208  0.2791      1.7
1   arguana  chamfer-sym   0.3435      0.8201  0.2825      2.6
2   arguana      sw L=64   0.1159      0.4950  0.0885      0.6
3   arguana     sw L=128   0.1754      0.6060  0.1349      0.6
4   arguana     sw L=256   0.2089      0.6465  0.1641      0.6
5   arguana     sw L=512   0.2268      0.6764  0.1785      0.7
6   arguana    sw L=1024   0.2409      0.6871  0.1902      0.9
7   arguana    sw L=2048   0.2424      0.6977  0.1922      1.2
8   scidocs      chamfer   0.1043      0.2636  0.2000     56.6
9   scidocs  chamfer-sym   0.0596      0.2319  0.1086      5.0
10  scidocs      sw L=64   0.0162      0.0920  0.0320      1.8
11  scidocs     sw L=128   0.0269      0.1187  0.0498      1.7
12  scidocs     sw L=256   0.0286      0.1377  0.0558      1.9
13  scidocs     sw L=512   0.0327      0.1468  0.0599      2.0
14  scidocs    sw L=1024   0.0359      0.1539  0.0675      2.4
15  scidocs    sw L=2048   0.0351      0.1570  0.0645      3.3
16    quora      chamfer   0.6582      0.8975  0.6543    304.9
17    quora  chamfer-sym   0.6593      0.9039  0.6560    131.6
18    quora      sw L=64   0.5442      0.7904  0.5434      7.7
19    quora     sw L=128   0.5811      0.8315  0.5771     11.4
20    quora     sw L=256   0.5916      0.8432  0.5867     17.9
21    quora     sw L=512   0.6017      0.8534  0.5973     30.0
22    quora    sw L=1024   0.6075      0.8583  0.6029     55.1
23    quora    sw L=2048   0.6090      0.8601  0.6039    107.9

In [22]:
# Side by side: one row per config, one column group per metric and dataset.
table.pivot(index="config", columns="dataset", values=list(METRICS)).reindex([c[0] for c in CONFIGS])

            ndcg@10                 recall@100                  mrr@10  \
dataset     arguana   quora scidocs    arguana   quora scidocs arguana
config
chamfer      0.3414  0.6582  0.1043     0.8208  0.8975  0.2636  0.2791
chamfer-sym  0.3435  0.6593  0.0596     0.8201  0.9039  0.2319  0.2825
sw L=64      0.1159  0.5442  0.0162     0.4950  0.7904  0.0920  0.0885
sw L=128     0.1754  0.5811  0.0269     0.6060  0.8315  0.1187  0.1349
sw L=256     0.2089  0.5916  0.0286     0.6465  0.8432  0.1377  0.1641
sw L=512     0.2268  0.6017  0.0327     0.6764  0.8534  0.1468  0.1785
sw L=1024    0.2409  0.6075  0.0359     0.6871  0.8583  0.1539  0.1902
sw L=2048    0.2424  0.6090  0.0351     0.6977  0.8601  0.1570  0.1922


dataset       quora scidocs
config
chamfer      0.6543  0.2000
chamfer-sym  0.6560  0.1086
sw L=64      0.5434  0.0320
sw L=128     0.5771  0.0498
sw L=256     0.5867  0.0558
sw L=512     0.5973  0.0599
sw L=1024    0.6029  0.0675
sw L=2048    0.6039  0.0645

In [ ]:
# table.to_csv("../results/ensemble.csv", index=False)